version: '2'

services:
  mongo-db:
    image: mongo:4.0
    container_name: looking-at-stock
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=secret
